Commit
yosuke1205/chatspace pull request #4
Opened 2019-03-10 07:42 UTC by yosuke1205

2019-03-10 07:54 UTC, yuki-uchida requested changes

2019-03-10 07:54 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +  function buildHTML(message).animate({scrolldown: 0}, 500, 'swing');{
buildHTMLでは、何をどうするのかがわかりづらいので、buildSendMessageHTMLとかいかがでしょうか

2019-03-10 07:54 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +     .done(function(data){
dataでは、何を受け取ったのかわからないので、それがわかる名前に変えましょう

2019-03-10 07:54 UTC, yuki-uchida commented
プルリクには必ずWHAT WHYを書いてください
なんのためにプルリクを出しているのかわかりません。

2019-03-11 09:38 UTC, yosuke1205 commented
# what
非同期通信を実装する

# why
実装に必要なため

2019-03-11 09:48 UTC, ghost requested changes

2019-03-11 09:48 UTC, hiroki5123 commented on config/application.rb
> +config.i18n.default_locale = :ja
インデント崩れてますので修正してください。

2019-03-11 09:48 UTC, hiroki5123 commented on app/assets/javascripts/message.js
> +    console.log(formData);
削除してください

2019-03-11 09:54 UTC, ghost requested changes

2019-03-11 09:54 UTC, hiroki5123 commented on config/application.rb
> +end
endの位置あってますか？

2019-03-11 10:13 UTC, ghost requested changes
コメントには返信をしてください

2019-03-11 10:13 UTC, hiroki5123 commented on app/controllers/messages_controller.rb
> +    respond_to do |format|
インデント修正してください

2019-03-11 10:13 UTC, hiroki5123 commented on app/assets/javascripts/message.js
> +  <p class="chat-message__upper-info__date">
画像が送信できる仕様になってないので修正してください。

2019-03-11 11:03 UTC, yosuke1205 commented on app/controllers/messages_controller.rb
> +    respond_to do |format|
コメントせずに申し訳ありません。
修正しました。

2019-03-11 11:03 UTC, yosuke1205 commented on app/assets/javascripts/message.js
> +  <p class="chat-message__upper-info__date">
画像送れるように反映しました。
ご確認のほどよろしくお願いします

2019-03-11 11:07 UTC, ghost requested changes

2019-03-11 11:07 UTC, hiroki5123 commented on app/controllers/messages_controller.rb
> +      respond_to do |format|
インデント修正する必要ありません

2019-03-11 11:07 UTC, hiroki5123 commented on app/assets/javascripts/message.js
> +      $('.form__message').val('')
.reset()を使いましょう

2019-03-11 11:26 UTC, yosuke1205 commented on app/assets/javascripts/message.js
> +      $('.form__message').val('')
お願いします！

2019-03-11 11:32 UTC, ghost approved these changes
LGTMです！

2019-03-11 14:42 UTC, merged